import {useEffect,useRef} from 'react';
import {agentNames,useAvatarTheme} from './AvatarTheme';
import {Close, Check, ArrowRight, BookOpen, Volume2, VolumeX, Sliders, Copy, Users, Flag, Crown, Play, Plus, Search, Upload, ChevronDown, ChevronRight, Home, Reload, FileText, Eye, EyeOff, InfoBox as Info, ArrowLeft, Trash, Download} from 'pixelarticons/react/index.js';
const icons={close:Close,check:Check,arrow:ArrowRight,book:BookOpen,sound:Volume2,mute:VolumeX,settings:Sliders,copy:Copy,users:Users,flag:Flag,crown:Crown,play:Play,plus:Plus,search:Search,upload:Upload,down:ChevronDown,right:ChevronRight,home:Home,reload:Reload,log:FileText,eye:Eye,hidden:EyeOff,info:Info,back:ArrowLeft,trash:Trash,download:Download};
export function Icon({name,size=22,...props}){const Component=icons[name]||Info;return <Component width={size} height={size} aria-hidden="true" {...props}/>;}
export const avatarNames=['幽灵','猫头鹰','小猫','小鸡','骰子','机器人','青蛙','恐龙','羚羊'];
export function Avatar({id=0,size=64,agentId}){const theme=useAvatarTheme();const isAgent=agentId!==undefined||!!theme;const index=agentId??(theme?theme[id]??0:id);return <span role="img" aria-label={isAgent?agentNames[index]:avatarNames[id]} className="avatar" style={{width:size,height:size,...(isAgent?{backgroundImage:'url(/assets/valorant-avatars.png)'}:{}),backgroundPosition:`${(index%3)*50}% ${Math.floor(index/3)*50}%`}}/>;}
export function AvatarPicker({value,onChange}){const theme=useAvatarTheme();const names=theme?theme.map(i=>agentNames[i]):avatarNames;return <div className="avatar-grid">{names.map((name,id)=><button type="button" aria-label={`选择${name}头像`} aria-pressed={value===id} className={`avatar-option ${value===id?'chosen':''}`} key={name} onClick={()=>onChange(id)}><Avatar id={id} size={76}/>{value===id&&<span className="check-corner"><Icon name="check" size={16}/></span>}</button>)}</div>;}
export function Button({children,icon,variant='',className='',...props}){return <button className={`button ${variant} ${className}`} {...props}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>;}
export function Modal({title,onClose,children,wide=false}){
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement;ref.current?.focus();const listener=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const a=[...ref.current.querySelectorAll('button:not([disabled]),input,select,textarea,a[href]')].filter(x=>x.offsetParent!==null);if(!a.length){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===a[0]||document.activeElement===ref.current)){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus();}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide?'wide':''}`}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><Icon name="close"/></button></div>{children}</section></div>;
}
export function Toggle({checked,onChange,label}){return <button type="button" className={`toggle ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>;}
