import {useState} from 'react';
import {Button,Icon} from './Common';
import {parseWordPack,mergeWords} from '../game/wordpacks';
export function WordLibrary({packs,selected,onSelect,onImport,onDelete}){
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('全部'),[importing,setImporting]=useState(false),[raw,setRaw]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(null);
 const categories=['全部',...new Set(packs.map(p=>p.category))];
 const visible=packs.filter(p=>(filter==='全部'||p.category===filter)&&`${p.name} ${p.description}`.toLowerCase().includes(search.toLowerCase()));
 function save(){try{const p=parseWordPack(raw,name||'我的词库');onImport(p);setImporting(false);setRaw('');setName('');setError('');}catch(e){setError(e.message);}}
 async function file(e){const f=e.target.files[0];if(!f)return;if(f.size>500000){setError('文件不能大于 500 KB');return;}setName(f.name.replace(/\.[^.]+$/,''));setRaw(await f.text());setError('');}
 function download(){const blob=new Blob([JSON.stringify({name:'我的主题词库',category:'自定义',language:'zh-CN',description:'在这里介绍你的词库',words:packs[0].words.slice(0,30)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='wordpack-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="library"><div className="library-summary"><div><p className="eyebrow">WORD LIBRARY</p><p>选一套熟悉的，或者混搭一点意外。</p></div><Button icon="upload" onClick={()=>setImporting(!importing)}>导入词库</Button></div>
 {importing?<div className="import-panel"><h3>添加你的词库</h3><p className="muted">粘贴词语（每行一个或逗号分隔），也可以导入 JSON 文件。</p><label>词库名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：朋友们的梗" maxLength={40}/></label><label>词语内容<textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'海洋\n月亮\n钢琴\n…至少 25 个不重复的词'} rows={7}/></label><div className="import-tools"><label className="file-label"><Icon name="upload"/>选择 TXT / JSON 文件<input type="file" accept=".txt,.json,text/plain,application/json" onChange={file}/></label><button className="text-button" onClick={download}>下载 JSON 模板</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="row end"><Button onClick={()=>setImporting(false)}>返回词库</Button><Button variant="primary" onClick={save}>保存词库</Button></div></div>:<><div className="search-field"><Icon name="search"/><input aria-label="搜索词库" placeholder="搜索词库名称或主题…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-tabs">{categories.map(c=><button className={filter===c?'active':''} key={c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="pack-grid">{visible.map(p=><article key={p.id} className={`pack ${selected.includes(p.id)?'selected':''}`}><button className="pack-select" aria-pressed={selected.includes(p.id)} onClick={()=>onSelect(selected.includes(p.id)?selected.filter(x=>x!==p.id):[...selected,p.id])}><div className="row between"><span className="tag">{p.category}</span><span className="checkbox">{selected.includes(p.id)&&<Icon name="check" size={18}/>}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="pack-meta"><span>{p.words.length} 个词</span><span>{p.language==='en'?'EN':'中文'}</span></div></button><div className="pack-tools"><button className="text-button" onClick={()=>setPreview(preview===p.id?null:p.id)}>{preview===p.id?'收起':'预览词语'}<Icon name="right" size={16}/></button>{p.custom&&<button className="text-button danger" onClick={()=>onDelete(p.id)} aria-label={`删除${p.name}`}><Icon name="trash" size={16}/></button>}</div>{preview===p.id&&<div className="word-preview">{p.words.slice(0,30).map(w=><span key={w}>{w}</span>)}{p.words.length>30&&<small>还有 {p.words.length-30} 个词</small>}</div>}</article>)}</div>{!visible.length&&<div className="empty-state">没有找到相关词库，试试其他关键词。</div>}<div className="library-footer"><span>已选 <strong>{selected.length}</strong> 套 · 去重后 <strong>{mergeWords(packs.filter(p=>selected.includes(p.id))).length}</strong> 个词</span><small>每局随机抽取 25 个</small></div></>}
 </div>;
}
