import {useEffect,useRef,useState} from 'react';
import {Avatar,AvatarPicker,Button,Icon,Modal,Toggle} from './components/Common';
import {OnlineTeams,PlayerAvatar} from './components/OnlineTeams';
import {WordLibrary} from './components/WordLibrary';
import {Rules} from './components/Rules';
import {builtInPacks} from './data/packs';
import {useRoom} from './game/network';
import {useRoomTools} from './game/webmcp';
import {playSound} from './game/audio';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d;}catch{return d;}};
const teamName=t=>t==='red'?'红队':t==='blue'?'蓝队':'合作小队';
export function App(){
 const net=useRoom(),{room,busy,connected}=net;
 useRoomTools(net);
 const [profile,setProfile]=useState(()=>read('cn-profile',{name:'',avatar:0}));
 const [settings,setSettings]=useState(()=>({...{sound:true,volume:35,guide:true,reduceMotion:false},...read('cn-settings',{})}));
 const [custom,setCustom]=useState(()=>read('cn-packs',[]));
 const [mode,setMode]=useState('coop'),[join,setJoin]=useState(()=>new URLSearchParams(location.search).get('room')||'');
 const [modal,setModal]=useState(null),[toast,setToast]=useState(''),[guide,setGuide]=useState(false),[selected,setSelected]=useState(null),[clue,setClue]=useState(''),[count,setCount]=useState('2'),[dismissedResult,setDismissedResult]=useState(null),[draftPacks,setDraftPacks]=useState([]);
 const game=room?.game,screen=game?'game':room?'lobby':'entry',coop=room?.mode==='coop',host=room?.host===room?.me,me=room?.players.find(p=>p.id===room.me),themed=room?.packIds.includes('valorant');
 const sound=type=>playSound(type,settings),previous=useRef(null);
 useEffect(()=>{try{localStorage.setItem('cn-profile',JSON.stringify(profile));}catch{}},[profile]);
 useEffect(()=>{try{localStorage.setItem('cn-settings',JSON.stringify(settings));}catch{}document.documentElement.dataset.motion=settings.reduceMotion?'off':'on';},[settings]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);}},[toast]);
 useEffect(()=>{const marker=game?`${game.id}:${game.step}`:null;if(previous.current!==marker){if(previous.current&&marker)sound(game.phase==='ended'?(game.winner==='loss'?'lose':'win'):game.phase==='clue'?'turn':'clue');previous.current=marker;setSelected(null);setClue('');setGuide(!!game&&settings.guide);}},[game?.id,game?.step]);
 const update=(k,v)=>setSettings(s=>({...s,[k]:v}));
 async function enter(isJoin=false){if(!profile.name.trim()){net.setError('先输入你的 Nickname');return;}if(isJoin&&!/^[A-Z2-9]{6}$/i.test(join.trim())){net.setError('请输入 6 位房间码');return;}await net.enter({...profile,name:profile.name.trim()},mode,isJoin?join.trim():null);}
 async function action(a){return net.action(a);}
 async function copy(){const url=new URL(location.href);url.search='';url.searchParams.set('room',room.code);try{await navigator.clipboard.writeText(url.href);setToast('邀请链接已复制，发给朋友就能加入');}catch{setToast(`房间码：${room.code}`);}}
 function openPacks(){setDraftPacks(room.packIds);setModal('packs');}
 async function savePacks(){if(await action({type:'configure',packIds:draftPacks,customPacks:custom.filter(p=>draftPacks.includes(p.id))}))setModal(null);}
 function importPack(p){try{const next=[...custom,p];localStorage.setItem('cn-packs',JSON.stringify(next));setCustom(next);setDraftPacks(x=>[...x,p.id]);}catch{setToast('浏览器存储空间不足');}}
 function deletePack(id){const next=custom.filter(p=>p.id!==id);try{localStorage.setItem('cn-packs',JSON.stringify(next));setCustom(next);setDraftPacks(x=>x.filter(k=>k!==id));}catch{setToast('无法更新本地词库');}}
 const resultTitle=coop?(game?.winner==='win'?'合作成功！':'挑战结束'):game?`${teamName(game.winner)}获胜！`:'';
 const actor=room?.players.find(p=>p.id===(game?.phase==='clue'?game?.cluer:game?.guesser));
 const turnText=game?.phase==='ended'?resultTitle:room?.paused?'等待队友重新连接':`${actor?.name||'队友'} · ${game?.phase==='clue'?'给出提示':'正在猜词'}`;
 const inactive=busy||!connected;
 return <div className={`app ${screen}`}><header className="topbar"><button className="wordmark" onClick={()=>room&&setModal('leave')} aria-label="回到首页">CODENAME</button>{room&&<div className="room-label"><span className="square"/>{room.code}<span className="room-mode">· {coop?'CO-OP':'CLASSIC'}</span></div>}<div className="top-actions"><Button icon="book" onClick={()=>setModal('rules')}>规则</Button><Button icon="settings" onClick={()=>setModal('settings')}>设置</Button><button className="icon-button" aria-label={settings.sound?'关闭音效':'打开音效'} onClick={()=>update('sound',!settings.sound)}><Icon name={settings.sound?'sound':'mute'}/></button></div></header>
 {net.session&&!room&&<div className="connection-banner">正在恢复房间… <button onClick={net.forget}>返回首页</button></div>}
 {room&&!connected&&<div role="status" className="connection-banner">连接中断，正在重连。恢复后可继续游戏。</div>}
 {net.error&&<div role="alert" className="network-error">{net.error}<button aria-label="关闭提示" onClick={()=>net.setError('')}>×</button></div>}
 {screen==='entry'&&!net.session&&<main className="entry-main"><section className="entry-hero"><h1>我还没有<br/>想好叫什么</h1></section><section className="welcome-panel"><h2 className="welcome"><span className="square blue"/>welcome<span className="square red"/></h2><form onSubmit={e=>{e.preventDefault();enter();}}><div className="profile-row"><div className="profile-preview"><Avatar id={profile.avatar} size={84}/></div><label>Nickname<input autoComplete="nickname" maxLength={16} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="你的昵称"/></label></div><h3 className="avatar-label">选择你的头像</h3><AvatarPicker value={profile.avatar} onChange={avatar=>setProfile({...profile,avatar})}/><div className="mode-picker" role="group" aria-label="游戏人数"><button type="button" className={mode==='coop'?'active':''} aria-pressed={mode==='coop'} onClick={()=>setMode('coop')}>2 人合作<small>轮流提示，一起找齐目标</small></button><button type="button" className={mode==='classic'?'active':''} aria-pressed={mode==='classic'} onClick={()=>setMode('classic')}>4 人对战<small>红蓝两队，比拼默契</small></button></div><Button disabled={busy} type="submit" variant="primary" className="create-room">{busy?'连接中…':'创建房间'}<Icon name="arrow"/></Button></form><div className="or-divider"><span>或</span></div><div className="join-row"><input aria-label="房间码" placeholder="6 位房间码" maxLength={6} value={join} onChange={e=>setJoin(e.target.value.toUpperCase())}/><Button disabled={busy} variant="blue" onClick={()=>enter(true)}>加入房间</Button></div></section></main>}
 {screen==='lobby'&&<main className="lobby-main"><h1 className="ready-title"><span className="square blue"/>Ready?<span className="square red"/></h1><div className="lobby-layout"><OnlineTeams room={room} onAction={action} busy={inactive}/><aside className="lobby-sidebar"><section className="invite-section"><h2>房间邀请</h2><button className="room-code" onClick={copy}><Icon name="copy"/><strong>{room.code}</strong></button><Button variant="primary" icon="copy" onClick={copy}>复制邀请链接</Button><small>朋友用自己的设备打开链接即可加入</small></section><section className="setup-section"><h3><Icon name="settings"/>游戏设置</h3><div className="setup-row"><span>模式</span><select aria-label="游戏模式" value={room.mode} disabled={!host||inactive} onChange={e=>action({type:'configure',mode:e.target.value})}><option value="coop">2 人合作</option><option value="classic">4 人对战</option></select></div><div className="setup-row"><span>词库</span><button disabled={!host||inactive} className="pack-picker" onClick={openPacks}>{room.packNames.join(' + ')}<Icon name="down"/></button></div><div className="pack-summary">{room.wordCount} 个词 · 每局随机 25 个{host&&<button className="text-button" onClick={openPacks}>管理词库</button>}</div>{!coop&&<div className="setup-row"><span>先手</span><select aria-label="先手队伍" disabled={!host||inactive} value={room.first} onChange={e=>action({type:'configure',first:e.target.value})}><option value="random">随机</option><option value="red">红队</option><option value="blue">蓝队</option></select></div>}<p className="muted small">{coop?'两人各自看到不同线索，9 回合内共同找到 15 个目标。':'每队一名情报员和一名猜词者，先找齐己方词语获胜。'}</p></section><section className="ready-section"><div className="row between"><h3>玩家已准备</h3><strong>{room.players.filter(p=>p.ready).length} / {coop?2:4}</strong></div><div className="ready-avatars">{room.players.map(p=><div key={p.id}><PlayerAvatar player={p} themed={themed} size={40}/>{p.ready&&<span><Icon name="check" size={12}/></span>}</div>)}</div><Button disabled={inactive} icon="check" onClick={()=>action({type:'ready',ready:!me.ready})}>{me.ready?'已准备 · 点击取消':'准备'}</Button>{host?<Button variant="primary" disabled={inactive||room.players.length!==(coop?2:4)||!room.players.every(p=>p.ready&&p.online)} onClick={()=>action({type:'start'})}>开始游戏</Button>:<p className="muted">准备后等待房主开始</p>}{!room.players.find(p=>p.id===room.host)?.online&&!host&&<Button disabled={inactive} onClick={()=>action({type:'claimHost'})}>接任离线房主</Button>}<button className="text-button" onClick={()=>setModal('leave')}>离开房间</button></section></aside></div></main>}
 {screen==='game'&&<main className="game-main"><div className="game-meta"><button className="text-button" onClick={()=>setModal('leave')}><Icon name="back" size={18}/>离开房间</button><span>第 {game.round}{coop?' / 9':''} 回合 · {room.packNames.join(' + ')}</span><strong>{coop?'两人合作':me.seat%2===0?'情报员':'猜词者'}</strong></div><div className={`turn-banner ${coop?'green':game.turn}`}><Icon name="flag"/>{turnText}<button aria-label="打开快捷引导" onClick={()=>setGuide(!guide)}><Icon name="info"/></button></div><div className="game-layout"><OnlineTeams room={room} onAction={action} busy={inactive}/><section className="board-area"><div className="word-board">{game.cards.map(card=><button key={card.id} className={`word-card ${card.type} ${card.revealed?'revealed':''} ${selected===card.id?'selected':''}`} disabled={inactive||!game.canGuess||card.blocked} onClick={()=>{setSelected(selected===card.id?null:card.id);setGuide(false);sound('click');}} aria-label={`${card.word}${card.revealed?' 已揭开':''}`} aria-pressed={selected===card.id}><span>{card.word}</span>{card.revealed&&<Icon name="check"/>}{selected===card.id&&<span className="candidate-avatar"><PlayerAvatar player={me} themed={themed} size={23}/></span>}</button>)}</div>
 {guide&&game.phase!=='ended'&&<aside className="quick-guide"><div className="row between"><strong>QUICK GUIDE</strong><button className="plain-icon" aria-label="关闭快捷引导" onClick={()=>setGuide(false)}><Icon name="close"/></button></div><h3>{game.canClue?'用一个词，连接目标':game.canGuess?'先选择，再确认翻牌':'等待队友行动'}</h3><p>{game.canClue?`根据${coop?'绿色目标':'己方颜色'}输入一个提示词和数量。`:game.canGuess?'点选卡牌，再确认猜测；小心刺客。':'只能由当前角色操作，请保持页面打开。'}</p><div className="row between"><button className="text-button" onClick={()=>setModal('rules')}>完整规则</button><label className="guide-auto"><input type="checkbox" checked={settings.guide} onChange={e=>update('guide',e.target.checked)}/>自动显示</label><Button onClick={()=>setGuide(false)}>知道了</Button></div></aside>}
 <div className="action-panel">{game.canClue?<form className="clue-form" onSubmit={async e=>{e.preventDefault();if(await action({type:'clue',word:clue,count:count==='infinity'?'infinity':Number(count)}))setGuide(false);}}><label>提示词<input value={clue} maxLength={20} onChange={e=>setClue(e.target.value)} placeholder="输入一个提示词…"/></label><label className="count-field">数量<select aria-label="提示数量" value={count} onChange={e=>setCount(e.target.value)}>{[0,1,2,3,4,5,6,7,8,9].map(n=><option key={n} value={n}>{n}</option>)}<option value="infinity">∞</option></select></label><Button disabled={inactive} type="submit" variant="primary">发送提示<Icon name="arrow"/></Button></form>:game.phase==='guess'?<><div className="clue-display"><span>提示词</span><strong>{game.clue.word}<span>× {game.clue.count==='infinity'?'∞':game.clue.count}</span></strong><small>{game.guessesLeft===null?'不限次数':`最多还可猜 ${game.guessesLeft} 次`}</small></div>{game.canGuess?<div className="guess-actions"><Button disabled={inactive||selected===null} variant="primary" onClick={()=>action({type:'guess',cardId:selected})}>确认猜{selected===null?'这张':`「${game.cards.find(c=>c.id===selected)?.word}」`}</Button><Button disabled={inactive||game.guessesMade===0} onClick={()=>action({type:'pass'})}>结束猜测</Button></div>:<p className="waiting">{room.paused?'等待队友重新连接':`${actor?.name} 正在猜词，请保持安静。`}</p>}</>:game.phase==='ended'?<div className="row between"><strong>{resultTitle}</strong>{host&&<Button disabled={inactive} onClick={()=>action({type:'lobby'})}>返回大厅</Button>}</div>:<div className="waiting"><Icon name="hidden"/>等待 {actor?.name} 给出提示</div>}</div><div className="board-footer"><span>{coop?`共同目标：${15-game.remaining.green} / 15`:'未揭开的身份仅情报员可见'}</span><span>{connected?'● 已连接':'重新连接中'}</span></div></section><aside className="game-log"><h3><Icon name="log"/>Game Log</h3><div className="log-entries" aria-live="polite">{room.logs.map(log=><div key={log.id} className="log-entry"><i className={log.team}/><p>{log.text}</p><time>{new Date(log.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time></div>)}</div></aside></div>{host&&game.phase!=='ended'&&<button className="text-button" onClick={()=>setModal('reset')}>结束本局并返回大厅</button>}{!host&&!room.players.find(p=>p.id===room.host)?.online&&<Button disabled={inactive} onClick={()=>action({type:'claimHost'})}>接任离线房主</Button>}</main>}
 {modal==='rules'&&<Modal title="游戏规则" wide onClose={()=>setModal(null)}><Rules mode={room?.mode||mode}/></Modal>}
 {modal==='packs'&&host&&!game&&<Modal title="选择词库" wide onClose={()=>setModal(null)}><WordLibrary packs={[...builtInPacks,...custom]} selected={draftPacks} onSelect={setDraftPacks} onImport={importPack} onDelete={deletePack}/><p className="muted">更换词库后，所有玩家需要重新准备。</p><Button disabled={inactive||!draftPacks.length} variant="primary" onClick={savePacks}>完成选择</Button></Modal>}
 {modal==='settings'&&<Modal title="设置" onClose={()=>setModal(null)}><section className="settings-group"><div className="setting-row"><strong>音效</strong><Toggle label="音效" checked={settings.sound} onChange={v=>update('sound',v)}/></div><div className="volume-row"><label htmlFor="volume">音量</label><input id="volume" type="range" min="0" max="100" value={settings.volume} onChange={e=>update('volume',Number(e.target.value))}/><span>{settings.volume}%</span><Button onClick={()=>sound('correct')}>试听</Button></div><div className="setting-row"><strong>自动显示快捷引导</strong><Toggle label="自动显示快捷引导" checked={settings.guide} onChange={v=>update('guide',v)}/></div><div className="setting-row"><strong>减少动画</strong><Toggle label="减少动画" checked={settings.reduceMotion} onChange={v=>update('reduceMotion',v)}/></div></section><Button className="full" variant="primary" onClick={()=>setModal(null)}>完成</Button></Modal>}
 {(modal==='leave'||modal==='reset')&&<Modal title={modal==='leave'?'离开房间？':'结束本局？'} onClose={()=>setModal(null)}><p>{game?'当前对局会结束，其他玩家将回到大厅。':'退出后会释放你的位置，房主离开时会自动转交。'}</p><div className="row end"><Button onClick={()=>setModal(null)}>取消</Button><Button disabled={inactive} variant="primary" onClick={async()=>{if(await action({type:modal==='leave'?'leave':'lobby'}))setModal(null);}}>确认</Button></div></Modal>}
 {game?.phase==='ended'&&dismissedResult!==game.id&&<Modal title="本局结束" onClose={()=>setDismissedResult(game.id)}><div className={`result ${coop?'green':game.winner}`}><Icon name="crown" size={50}/><h2>{resultTitle}</h2><p>{game.reason==='assassin'?'翻到了刺客。':game.reason==='time'?'9 个回合已用完。':'所有目标词语已找到。'}</p><div className="result-avatars">{room.players.filter(p=>coop||Math.floor(p.seat/2)===(game.winner==='red'?0:1)).map(p=><PlayerAvatar key={p.id} player={p} themed={themed} size={74}/>)}</div>{host?<Button disabled={inactive} variant="primary" onClick={()=>action({type:'lobby'})}>返回大厅 · 再来一局</Button>:<p>等待房主返回大厅</p>}<Button onClick={()=>setDismissedResult(game.id)}>查看棋盘</Button></div></Modal>}
 {toast&&<div className="toast" role="status">{toast}</div>}
 </div>;
}
